02_Django路由Router/DjangoPro2/App/urls.py
from django.urls import path, re_path
from App.views import *

urlpatterns = [
    # 首页
    path('index/', index, name='index'),

    # 用户列表
    path('userlist/', user_list, name='userlist'),

    # 用户详情
    # 单个参数
    path('userdetail/<int:uid>/', user_detail, name='userdetail'),

    # 多个参数
    path('userab/<int:a>/<int:b>/', user_ab_view, name='userab'),
    # <int: a> 整数
    # <str: a> 字符型
    path('userba/<int:a>/<int:b>/', user_ba_view, name='userba'),
    # 正则的写法
    # re_path(r'userba/(?P<a>\d+)/(?P<b>\d+)/', user_ba_view, name='userba')

    # 重定向
    path('myredirect/', my_redirect),

]

02_Django路由Router/DjangoPro2/DjangoPro2/urls.py
from django.contrib import admin
from django.urls import path, include
from App.views import *

urlpatterns = [

    # 1. 直接使用根路由
    # path('user/', index),

    # 2. 使用子路由: 使用include
    # path('user/', include('App.urls')),

    # 3.使用子路由: 使用include, 命名空间 namespace
    path('user/', include(('App.urls', 'App'), namespace='App')),

    path('admin/', admin.site.urls),
]

02_Django路由Router/DjangoPro2/App/models.py
from django.db import models

class userModel(models.Model):
    name = models.CharField(max_length=30)
    age = models.PositiveIntegerField()  # 非负数

02_Django路由Router/DjangoPro2/App/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from App.models import *

# Create your views here.
# 首页
def index(request):
    return render(request, 'index.html')

# 用户列表
def user_list(request):
    users = userModel.objects.all()
    return render(request, 'user_list.html', {'users': users})

# 用户详情
def user_detail(request, uid):
    print('uid', uid)
    user = userModel.objects.get(pk=uid)  # pk: primary key 主键
    return render(request, 'user_detail.html', {'user': user})

# 多个参数
def user_ab_view(request, a, b):
    return HttpResponse(f'a:{a} - b:{b}')

# 要和路由中的参数名一致, 名字对应赋值
def user_ba_view(request, b, a):
    return HttpResponse(f'a:{a} - b:{b}')

# 重定向
def my_redirect(request):
    # return redirect('https://www.pinterest.com')
    # return redirect('/user/userlist')
    # return redirect('/user/userdetail/2')

    # 使用反向解析
    # 带命名空间的写法
    # return redirect(reverse('App:userdetail', args=(2,)))  # 位置参数传参
    return redirect(reverse('App:userdetail', kwargs={'uid': 2}))  # 关键字传参
    # 不带命名空间的写法
    # return redirect(reverse('userdetail', args=(2,)))

02_Django路由Router/DjangoPro2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>首页</h2>
    <hr>

    {#  url路由  #}
    <a href="/user/userlist/">url路由的方式: 进入用户列表页面</a>
    <hr>
    
    {#  反向解析  #}
    {# userlist 是path路由的name值 #}
{#    <a href="{% url 'userlist' %}">反向解析的方式: 进入用户列表页面</a>#}
{#    <hr>#}

    {# 反向解析: 带命名空间 #}
    <a href="{% url 'App:userlist' %}">反向解析带命名空间的方式: 进入用户列表页面</a>
    
</body>
</html>

02_Django路由Router/DjangoPro2/templates/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户详情</title>
</head>
<body>
    <h2>用户详情</h2>
    <hr>

    <p>用户名字: {{ user.name }}</p>
    <p>用户年龄: {{ user.age }}</p>
</body>
</html>

02_Django路由Router/DjangoPro2/templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户列表</title>
</head>
<body>
    <h2>用户列表</h2>
    <hr>
    <ul>
        {# 'users是字典中的key'#}
        {% for user in users %}
            <li>
                {# 反向解析: 路由传参 #}
                <a href="{% url 'App:userdetail' user.id %}">
                    {{ user.name }} - {{ user.age }}
                </a>
            </li>
        	
        {% endfor %}
        
    </ul>
</body>
</html>