09_Django静态文件和文件上传/DjangoPro1/DjangoPro1/urls.py
from django.contrib import admin
from django.urls import path
from App.views import *

urlpatterns = [
    # 静态文件
    path('index/', index, name='index'),
    path('index2/', index2, name='index2'),

    # 上传文件
    path('upload1/', upload1, name='upload1'),
    path('upload2/', upload2, name='upload2'),

    path('showicon/', show_icon, name='showicon'),

    path('admin/', admin.site.urls),
]

09_Django静态文件和文件上传/DjangoPro1/App/models.py
from django.db import models

# 用户
class UserModel(models.Model):
    # 名字
    name = models.CharField(max_length=30, unique=True)
    # 头像路径
    icon = models.CharField(max_length=255)

# 相册
class PhotoModel(models.Model):
    # 图片链接
    # 图片所属用户
    img = models.CharField(max_length=255)
    user = models.ForeignKey(UserModel, on_delete=models.PROTECT)

09_Django静态文件和文件上传/DjangoPro1/App/views.py
import os
import uuid

from django.shortcuts import render, redirect, reverse
from django.conf import settings

from App.models import *


# 静态文件的使用
def index(request):
    return render(request, 'index.html')

def index2(request):
    return render(request, 'index2.html')

# 上传文件: 媒体文件
def upload1(request):
    if request.method == 'GET':
        return render(request, 'upload1.html')
    elif request.method == 'POST':
        uname = request.POST.get('uname')
        icon = request.FILES.get('icon')  # 单个文件
        # print(icon, type(icon))
        # 1.jpg <class 'django.core.files.uploadedfile.InMemoryUploadedFile'>
        # print(icon.name)  # 1.jpg

        # 1. 将上传的图片存储到后台对应的媒体文件中
        file_name = gen_uuid_name() + os.path.splitext(icon.name)[-1]  # 接受一个路径作为参数，并返回一个元组，其中第一个元素是路径（不包括扩展名），第二个元素是扩展名
        file_path = os.path.join(settings.MEDIA_ROOT, file_name)

        with open(file_path, 'ab') as fp:
            for part in icon.chunks():
                fp.write(part)
                fp.flush()  # 清空缓存
        # 2. 将该媒体文件的路径, 存入到数据库中
        user = UserModel()
        user.name = uname
        user.icon = 'uploads/' + file_name
        user.save()

        return redirect(reverse('showicon'))

# 通过uuid来得到唯一的图片名称
def gen_uuid_name():
    return str(uuid.uuid4())

# 显示图片
def show_icon(request):
    user = UserModel.objects.get(pk=2)
    return render(request, 'showicon.html', {'user': user})

# 多文件上传
def upload2(request):
    if request.method == 'GET':
        return render(request, 'upload2.html')
    elif request.method == 'POST':
        # 接受前端提交过来的数据
        uname = request.POST.get('uname')
        imgs = request.FILES.getlist('imgs')
        for img in imgs:
            # 1. 把图片存储到uploads中
            file_name = gen_uuid_name() + os.path.splitext(img.name)[-1]
            file_path = os.path.join(settings.MEDIA_ROOT, file_name)
            with open(file_path, 'ab') as fp:
                for part in img.chunks():
                    fp.write(part)
                    fp.flush()

            # 2.将图片路径存入到数据库中
            photo = PhotoModel()
            photo.img = 'uploads/' + file_name
            photo.user = UserModel.objects.filter(name=uname).first()
            photo.save()


        return redirect(reverse('showicon'))

09_Django静态文件和文件上传/DjangoPro1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
{#    <link rel="stylesheet" href="/static/index.css">#}
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>
<body>
    <h2>使用静态文件</h2>
    <hr>
</body>
</html>

09_Django静态文件和文件上传/DjangoPro1/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index2.css' %}">
</head>
<body>
    <h2>静态文件的使用</h2>
    <hr>
    
    # 加载图片
    <img src="{% static 'image/21.jpg' %}" alt="">
    <script src="{% static 'js/index2.js' %}"></script>
</body>
</html>

09_Django静态文件和文件上传/DjangoPro1/templates/showicon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
</head>
<body>
    <h2>显示用户</h2>
    <hr>
    <p>用户名: {{ user.name }}</p>
    <p>头像: <img src="{% static user.icon %}" alt="" width="200"></p>
    <hr>
    <h3>{{ user.name }}的相册</h3>
    {% for photo in user.photomodel_set.all %}
        <img src="{% static photo.img %}" alt="" width="100">
    {% endfor %}
    
</body>
</html>

09_Django静态文件和文件上传/DjangoPro1/templates/upload1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>单文件上传</title>
</head>
<body>
    <h2>单文件上传</h2>
    <hr>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>用户名: <input type="text" name="uname"></p>
        <p>头像: <input type="file" name="icon"></p>
        <p><button>上传图片</button></p>
    </form>
</body>
</html>

09_Django静态文件和文件上传/DjangoPro1/templates/upload2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>单文件上传</title>
</head>
<body>
    <h2>单文件上传</h2>
    <hr>
{#    enctype="multipart/form-data" 是为了支持文件上传  #}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>用户名: <input type="text" name="uname"></p>
        <p>请选择要上传的照片: <input type="file" name="imgs" multiple></p>
        <p><button>上传图片</button></p>
    </form>
</body>
</html>