06_Django模型综合项目/DjangoPro1/DjangoPro1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 子路由, 使用命名空间
    path('author/', include(('author.urls', 'author'), namespace='author')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('publisher/', include(('publisher.urls', 'publisher'), namespace='publisher')),

    path('admin/', admin.site.urls),
]

# 1.在书籍的book_index.html中有⼀个"查看所有书籍"的超链接按钮，点击进⼊书籍列表book_list.html⻚⾯.
# 2.在书籍的book_list.html中显示所有书名，点击书名可以进⼊书籍详情book_detail.html（通过书籍id）
# 3.在书籍book_detail.html中可以点击该书的作者和出版社，进⼊作者详情的author_detail.html和出版社详情的publisher_detail.html⻚⾯

06_Django模型综合项目/DjangoPro1/author/urls.py
from django.urls import path
from author.views import *

urlpatterns = [
    path('detail/<int:aid>/', author_detail, name='detail')
]

06_Django模型综合项目/DjangoPro1/book/urls.py
from django.urls import path
from book.views import *

urlpatterns = [
    path('index/', book_index, name='index'),
    path('list/', book_list, name='list'),
    path('detail/<int:bid>/', book_detail, name='detail'),
]

06_Django模型综合项目/DjangoPro1/publisher/urls.py
from django.urls import path
from publisher.views import *

urlpatterns = [
    path('detail/<int:pid>/', publisher_detail, name='detail'),
]

06_Django模型综合项目/DjangoPro1/author/models.py
from django.db import models

class Author(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    gender = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name + self.last_name

06_Django模型综合项目/DjangoPro1/book/models.py
from django.db import models
from author.models import *
from publisher.models import *

class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='书名')
    publish_date = models.DateField(verbose_name='出版时间')
    # 外键，book:author = N:1
    # on_delete=models.CASCADE: 级联删除
    author = models.ForeignKey(Author, on_delete=models.PROTECT, verbose_name='作者')
    # 多对多关系，book:publisher=N:N
    publishers = models.ManyToManyField(Publisher, verbose_name='出版社')

    def __str__(self):
        return self.title

06_Django模型综合项目/DjangoPro1/publisher/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=30)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=20)
    website = models.URLField()

    def __str__(self):
        return self.name

06_Django模型综合项目/DjangoPro1/author/views.py
from django.shortcuts import render
from author.models import *

# 作者详情
def author_detail(request, aid):
    # 获取aid对应的作者
    author = Author.objects.get(pk=aid)
    return render(request, 'author/author_detail.html', {'author': author})

06_Django模型综合项目/DjangoPro1/book/views.py
from django.shortcuts import render
from book.models import *

# 书籍首页
def book_index(request):
    return render(request, 'book/book_index.html')

# 书籍列表页
def book_list(request):
    # 获取所有书籍数据
    books = Book.objects.all()
    return render(request, 'book/book_list.html', {'books': books})

# 书籍详情页
def book_detail(request, bid):
    # 获取bid对应的书籍
    book = Book.objects.get(pk=bid)
    return render(request, 'book/book_detail.html', {'book': book})

06_Django模型综合项目/DjangoPro1/publisher/views.py
from django.shortcuts import render
from publisher.models import *

# 出版社详情
def publisher_detail(request, pid):
    # 获取pid对应的出版社数据
    publisher = Publisher.objects.get(pk=pid)
    return render(request, 'publisher/publisher_detail.html', {'publisher': publisher})

06_Django模型综合项目/DjangoPro1/templates/book/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍详情</title>
</head>
<body>
    <h2>书籍详情</h2>
    <hr>

    <p>书籍名称: {{ book.title }}</p>
    <p>书籍出版时间: {{ book.publish_date }}</p>
    <p>作者:
        <a href="{% url 'author:detail' book.author_id %}">
            {{ book.author.first_name }}{{ book.author.last_name }}
        </a>
    </p>
    <p>出版社:
        {% for publisher in book.publishers.all %}
            <a href="{% url 'publisher:detail' publisher.id %}">
                {{ publisher.name }}
            </a>
            {% if not forloop.last %}
                |
            {% endif %}
        {% endfor %}

    </p>
</body>
</html>

06_Django模型综合项目/DjangoPro1/templates/book/book_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍首页</title>
</head>
<body>
    <h2>书籍首页</h2>
    <hr>
    <a href="{% url 'book:list' %}">查看所有书籍</a>
</body>
</html>

06_Django模型综合项目/DjangoPro1/templates/book/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍列表</title>
</head>
<body>
    <h2>书籍列表</h2>
    <hr>
    
    <ul>
        {% for book in books %}
        	<li>
                <a href="{% url 'book:detail' book.id %}">
                    {{ book.title }}
                </a>
            </li>
        {% endfor %}
        
    </ul>
</body>
</html>

06_Django模型综合项目/DjangoPro1/templates/publisher/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>出版社详情</title>
</head>
<body>
    <h2>出版社详情</h2>
    <hr>
    
    <p>出版社名字: {{ publisher.name }}</p>
    <p>出版社地址: {{ publisher.address }}</p>
    <p>出版社城市: {{ publisher.city }}</p>
    <p>出版社省份: {{ publisher.state_province }}</p>
    <p>出版社国家: {{ publisher.country }}</p>
    <p>出版社网址: {{ publisher.website }}</p>

    <h4>我出版的所有书籍</h4>
    <ul>
        {% for book in publisher.book_set.all %}
        	<li>
                <a href="{% url 'book:detail' book.id %}">
                    {{ book.title }}
                </a>
            </li>
        {% endfor %}
        
    </ul>
</body>
</html>